// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckMove.API.DAL.Models;

#nullable disable

namespace TruckMove.API.DAL.Migrations
{
    [DbContext(typeof(TrukMoveContext))]
    [Migration("20240717112313_2024-7-17")]
    partial class _2024717
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence<int>("JobSeq")
                .StartsAt(2475L);

            modelBuilder.Entity("TruckMove.API.DAL.Models.Accommodation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Assignee")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Driver")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OrganiseNow")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Assignee");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Driver");

                    b.HasIndex("JobId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Accommodation", (string)null);
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Acknowledgement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Acknowledge")
                        .HasColumnType("bit");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("LegId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex(new[] { "LegId" }, "UQ_Acknowledge_LegId")
                        .IsUnique();

                    b.ToTable("Acknowledgement", (string)null);
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PermitAndPlateId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PermitAndPlateId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Checklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AirAndElectrics")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AllLightsAndIndicators")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CheckInsideTruckTrailer")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CheckTruckHeight")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrontDamage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("FuelLevel")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<bool?>("IsPre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("JackAndTools")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("KeysFobTotalKeys")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeftHandDamage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("NotesId")
                        .HasColumnType("int");

                    b.Property<string>("Oil")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("OwnersManual")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("PhotosId")
                        .HasColumnType("int");

                    b.Property<string>("RearDamage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RightHandDamage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SpareRim")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TyresCondition")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("VehicleCleanFreeOfRubbish")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VisuallyDipAndCheckTaps")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Water")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("WindscreenDamageWipers")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("JobId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Checklist", (string)null);
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountsEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyABN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyStreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimaryEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedById" }, "IX_Companies_CreatedById");

                    b.HasIndex(new[] { "UpdatedById" }, "IX_Companies_UpdatedById");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("ContactLandline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactStreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactsEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CompanyId" }, "IX_Contacts_CompanyId");

                    b.HasIndex(new[] { "CreatedById" }, "IX_Contacts_CreatedById");

                    b.HasIndex(new[] { "UpdatedById" }, "IX_Contacts_UpdatedById");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.HookupType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("HookupTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "HU Single",
                            Type = "HU_Single"
                        },
                        new
                        {
                            Id = 2,
                            Description = "HU Double",
                            Type = "HU_Double"
                        },
                        new
                        {
                            Id = 3,
                            Description = "4RA (4 Rigid Axle )",
                            Type = "FOUR_RA"
                        });
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TrailerId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("JobId");

                    b.HasIndex("TrailerId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("VehicleId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("Controller")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Driver")
                        .HasColumnType("int");

                    b.Property<string>("DropOfCoordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DropOfLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("EstimatedDaysofTravel")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EstimatedDeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupCoordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PickupDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PickupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<double?>("TotalDistance")
                        .HasColumnType("float");

                    b.Property<double?>("TotalDrivingTime")
                        .HasColumnType("float");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Driver");

                    b.HasIndex("Status");

                    b.HasIndex(new[] { "CompanyId" }, "IX_Jobs_CompanyId");

                    b.HasIndex(new[] { "Controller" }, "IX_Jobs_Controller");

                    b.HasIndex(new[] { "CreatedById" }, "IX_Jobs_CreatedById");

                    b.HasIndex(new[] { "UpdatedById" }, "IX_Jobs_UpdatedById");

                    b.HasIndex(new[] { "VehicleId" }, "UQ_Jobs_VehicleId")
                        .IsUnique()
                        .HasFilter("[VehicleId] IS NOT NULL");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.JobContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex(new[] { "ContactId" }, "IX_JobContacts_ContactId");

                    b.HasIndex(new[] { "JobId" }, "IX_JobContacts_JobId");

                    b.ToTable("JobContacts");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.JobSequence", b =>
                {
                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.ToTable("JobSequence", (string)null);
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.JobStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("JobStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A job that has been created in the system but does not have the minimum required information to complete the booking",
                            Status = "Planned"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A job that has the minimum required information (pickup location, dropoff location, vehicle information, assigned driver)",
                            Status = "Booked"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A booked job that is on or passed the pickup date.",
                            Status = "ReadyForPickup"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Status once the driver has arrived to pick up the truck and is done the pre departure check",
                            Status = "PreDepartureChecked"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Driver has completed the acknowledgement ",
                            Status = "Acknowledged"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A job that is currently in progress",
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 7,
                            Description = "status when driver stops for the night",
                            Status = "Stopped"
                        },
                        new
                        {
                            Id = 8,
                            Description = "status when driver stops for the night",
                            Status = "Delayed"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A job that has arrived at the destination",
                            Status = "Arrived"
                        },
                        new
                        {
                            Id = 10,
                            Description = "status when driver is competed arrival checklist",
                            Status = "ArrivalChecked"
                        },
                        new
                        {
                            Id = 11,
                            Description = "QA completed",
                            Status = "QADone"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Payment Done",
                            Status = "PaymentDone"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Billing Done",
                            Status = "BillingDone"
                        },
                        new
                        {
                            Id = 14,
                            Description = "A job that has been completed successfully",
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Leg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("EndLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegNumber")
                        .HasColumnType("int");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double?>("TotalDistance")
                        .HasColumnType("float");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int>("Variance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("JobId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("Variance");

                    b.ToTable("Legs");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.LegStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nchar(20)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("LegStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Planned"
                        },
                        new
                        {
                            Id = 2,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AccommodationId")
                        .HasColumnType("int");

                    b.Property<int?>("ChecklistId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermitAndPlatesId")
                        .HasColumnType("int");

                    b.Property<int?>("PublicTransportId")
                        .HasColumnType("int");

                    b.Property<int?>("TrailerId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.Property<bool?>("VisibletoDriver")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("JobId");

                    b.HasIndex("PermitAndPlatesId");

                    b.HasIndex("PublicTransportId");

                    b.HasIndex("TrailerId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("VehicleId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.PermitsAndPlate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Assignee")
                        .HasColumnType("int");

                    b.Property<double?>("CostForPermit")
                        .HasColumnType("float");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OrganiseNow")
                        .HasColumnType("bit");

                    b.Property<string>("PermitNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Assignee");

                    b.HasIndex("JobId");

                    b.HasIndex("Status");

                    b.HasIndex(new[] { "CreatedById" }, "IX_PermitsAndPlate_CreatedById");

                    b.HasIndex(new[] { "UpdatedById" }, "IX_PermitsAndPlate_UpdatedById");

                    b.ToTable("PermitsAndPlates");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.PublicTransport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ArrivalAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ArrivalDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("Assignee")
                        .HasColumnType("int");

                    b.Property<string>("BookingInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Daterequired")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartureAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DepartureDateTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("Driver")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OrganizeNow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Requiredsuburb")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requiredsuburb");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double?>("TransportCost")
                        .HasColumnType("float");

                    b.Property<int?>("TransportType")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Assignee");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Driver");

                    b.HasIndex("JobId");

                    b.HasIndex("Status");

                    b.HasIndex("TransportType");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PublicTransport", (string)null);
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.PublicTransportType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("PublicTransportTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Train"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Plane"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Uber"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Taxi"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Other"
                        });
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Assignee")
                        .HasColumnType("int");

                    b.Property<double?>("Cost")
                        .HasColumnType("float");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Driver")
                        .HasColumnType("int");

                    b.Property<bool?>("FromMobile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<bool?>("IsFuel")
                        .HasColumnType("bit");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Liters")
                        .HasColumnType("float");

                    b.Property<bool?>("OrganiseNow")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("ReciptUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Assignee");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Driver");

                    b.HasIndex("JobId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Purchase", (string)null);
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "OpsManager"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "AdminTeam"
                        },
                        new
                        {
                            Id = 4,
                            RoleName = "PayrollTeam"
                        },
                        new
                        {
                            Id = 5,
                            RoleName = "Driver"
                        });
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.TaskStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TaskStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Planned"
                        },
                        new
                        {
                            Id = 2,
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Trailer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DropOffLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HookupLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HookupType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rego")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("HookupType");

                    b.HasIndex("JobId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Trailers");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedById" }, "IX_Users_CreatedById");

                    b.HasIndex(new[] { "UpdatedById" }, "IX_Users_UpdatedById");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedById" }, "IX_UserRole_CreatedById");

                    b.HasIndex(new[] { "RoleId" }, "IX_UserRole_RoleId");

                    b.HasIndex(new[] { "UpdatedById" }, "IX_UserRole_UpdatedById");

                    b.HasIndex(new[] { "UserId" }, "IX_UserRole_UserId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Variance", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Variances");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Default",
                            Name = "_default"
                        },
                        new
                        {
                            Id = 1,
                            Description = "DG",
                            Name = "DG"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sat Rate",
                            Name = "Sat_rate"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sun Rate",
                            Name = "Sun_rate"
                        },
                        new
                        {
                            Id = 4,
                            Description = "G7",
                            Name = "G7"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Public Holiday",
                            Name = "Public_Holiday"
                        },
                        new
                        {
                            Id = 6,
                            Description = "G4",
                            Name = "G4"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Booking (Bullbar)",
                            Name = "Bookining_Bullbar"
                        });
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Colour")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(1)))");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<string>("Rego")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("VIN")
                        .IsFixedLength();

                    b.Property<string>("Year")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex(new[] { "JobId" }, "UQ_Vehicles_JobId")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.WayPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Coordinates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("WayPoints");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Accommodation", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "AssigneeNavigation")
                        .WithMany("AccommodationAssigneeNavigations")
                        .HasForeignKey("Assignee")
                        .HasConstraintName("FK_Accommodation_Users1");

                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany("AccommodationCreatedBies")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.User", "DriverNavigation")
                        .WithMany("AccommodationDriverNavigations")
                        .HasForeignKey("Driver")
                        .HasConstraintName("FK_Accommodation_Users");

                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("Accommodations")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Accommodation_Jobs");

                    b.HasOne("TruckMove.API.DAL.Models.TaskStatus", "StatusNavigation")
                        .WithMany("Accommodations")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK_Accommodation_TaskStatus");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany("AccommodationUpdatedBies")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("AssigneeNavigation");

                    b.Navigation("CreatedBy");

                    b.Navigation("DriverNavigation");

                    b.Navigation("Job");

                    b.Navigation("StatusNavigation");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Acknowledgement", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("Acknowledgements")
                        .HasForeignKey("JobId")
                        .HasConstraintName("FK_Acknowledgement_Jobs");

                    b.HasOne("TruckMove.API.DAL.Models.Leg", "Leg")
                        .WithOne("Acknowledgement")
                        .HasForeignKey("TruckMove.API.DAL.Models.Acknowledgement", "LegId")
                        .IsRequired()
                        .HasConstraintName("FK_Acknowledgement_Legs");

                    b.Navigation("Job");

                    b.Navigation("Leg");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Attachment", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.Accommodation", "Accommodation")
                        .WithMany("Attachments")
                        .HasForeignKey("AccommodationId")
                        .HasConstraintName("FK_TaskAttachments_Accommodation");

                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.PermitsAndPlate", "PermitAndPlate")
                        .WithMany("Attachments")
                        .HasForeignKey("PermitAndPlateId")
                        .HasConstraintName("FK_TaskAttachments_PermitsAndPlates");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Accommodation");

                    b.Navigation("CreatedBy");

                    b.Navigation("PermitAndPlate");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Checklist", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("Checklists")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_PreDepartureChecklist_Jobs");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("Job");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Company", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany("CompanyCreatedBies")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany("CompanyUpdatedBies")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Contact", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany("ContactCreatedBies")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany("ContactUpdatedBies")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Company");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Image", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("Images")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Images_Jobs");

                    b.HasOne("TruckMove.API.DAL.Models.Trailer", "Trailer")
                        .WithMany("Images")
                        .HasForeignKey("TrailerId")
                        .HasConstraintName("FK_Images_Trailers");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("Images")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("FK_Images_Vehicles");

                    b.Navigation("CreatedBy");

                    b.Navigation("Job");

                    b.Navigation("Trailer");

                    b.Navigation("UpdatedBy");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Job", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckMove.API.DAL.Models.User", "ControllerNavigation")
                        .WithMany("JobControllerNavigations")
                        .HasForeignKey("Controller");

                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany("JobCreatedBies")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.User", "DriverNavigation")
                        .WithMany("JobDriverNavigations")
                        .HasForeignKey("Driver")
                        .HasConstraintName("FK_Jobs_Users");

                    b.HasOne("TruckMove.API.DAL.Models.JobStatus", "StatusNavigation")
                        .WithMany("Jobs")
                        .HasForeignKey("Status")
                        .HasConstraintName("FK_Jobs_JobStatus");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany("JobUpdatedBies")
                        .HasForeignKey("UpdatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Vehicle", "Vehicle")
                        .WithOne("Job")
                        .HasForeignKey("TruckMove.API.DAL.Models.Job", "VehicleId")
                        .HasConstraintName("FK_Jobs_Vehicles");

                    b.Navigation("Company");

                    b.Navigation("ControllerNavigation");

                    b.Navigation("CreatedBy");

                    b.Navigation("DriverNavigation");

                    b.Navigation("StatusNavigation");

                    b.Navigation("UpdatedBy");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.JobContact", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.Contact", "Contact")
                        .WithMany("JobContacts")
                        .HasForeignKey("ContactId")
                        .IsRequired()
                        .HasConstraintName("FK_JobContacts_Contacts");

                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("JobContacts")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_JobContacts_Jobs");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("Contact");

                    b.Navigation("CreatedBy");

                    b.Navigation("Job");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Leg", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("Legs")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Legs_Jobs");

                    b.HasOne("TruckMove.API.DAL.Models.LegStatus", "StatusNavigation")
                        .WithMany("Legs")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK_Legs_LegStatus");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Variance", "VarianceNavigation")
                        .WithMany("Legs")
                        .HasForeignKey("Variance")
                        .IsRequired()
                        .HasConstraintName("FK_Legs_Variances");

                    b.Navigation("CreatedBy");

                    b.Navigation("Job");

                    b.Navigation("StatusNavigation");

                    b.Navigation("UpdatedBy");

                    b.Navigation("VarianceNavigation");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Note", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.Accommodation", "Accommodation")
                        .WithMany("Notes")
                        .HasForeignKey("AccommodationId")
                        .HasConstraintName("FK_Notes_Accommodation");

                    b.HasOne("TruckMove.API.DAL.Models.Checklist", "Checklist")
                        .WithMany("Notes")
                        .HasForeignKey("ChecklistId")
                        .HasConstraintName("FK_Notes_Checklist");

                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("Notes")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Notes_Jobs");

                    b.HasOne("TruckMove.API.DAL.Models.PermitsAndPlate", "PermitAndPlates")
                        .WithMany("Notes")
                        .HasForeignKey("PermitAndPlatesId")
                        .HasConstraintName("FK_Notes_PermitsAndPlates");

                    b.HasOne("TruckMove.API.DAL.Models.PublicTransport", "PublicTransport")
                        .WithMany("Notes")
                        .HasForeignKey("PublicTransportId")
                        .HasConstraintName("FK_Notes_PublicTransport");

                    b.HasOne("TruckMove.API.DAL.Models.Trailer", "Trailer")
                        .WithMany("Notes")
                        .HasForeignKey("TrailerId")
                        .HasConstraintName("FK_Notes_Trailers");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Vehicle", "Vehicle")
                        .WithMany("Notes")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("FK_Notes_Vehicles");

                    b.Navigation("Accommodation");

                    b.Navigation("Checklist");

                    b.Navigation("CreatedBy");

                    b.Navigation("Job");

                    b.Navigation("PermitAndPlates");

                    b.Navigation("PublicTransport");

                    b.Navigation("Trailer");

                    b.Navigation("UpdatedBy");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.PermitsAndPlate", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "AssigneeNavigation")
                        .WithMany("PermitsAndPlates")
                        .HasForeignKey("Assignee")
                        .HasConstraintName("FK_PermitsAndPlates_Users");

                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany("PermitsAndPlatesCreatedBies")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("PermitsAndPlates")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_PermitsAndPlates_Jobs");

                    b.HasOne("TruckMove.API.DAL.Models.TaskStatus", "StatusNavigation")
                        .WithMany("PermitsAndPlates")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK_PermitsAndPlates_TaskStatus");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany("PermitsAndPlatesUpdatedBies")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("AssigneeNavigation");

                    b.Navigation("CreatedBy");

                    b.Navigation("Job");

                    b.Navigation("StatusNavigation");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.PublicTransport", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "AssigneeNavigation")
                        .WithMany("PublicTransportAssigneeNavigations")
                        .HasForeignKey("Assignee")
                        .HasConstraintName("FK_PublicTransport_Users1");

                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany("PublicTransportCreatedBies")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.User", "DriverNavigation")
                        .WithMany("PublicTransportDriverNavigations")
                        .HasForeignKey("Driver")
                        .HasConstraintName("FK_PublicTransport_Users");

                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("PublicTransports")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_PublicTransport_Jobs");

                    b.HasOne("TruckMove.API.DAL.Models.TaskStatus", "StatusNavigation")
                        .WithMany("PublicTransports")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK_PublicTransport_TaskStatus");

                    b.HasOne("TruckMove.API.DAL.Models.PublicTransportType", "TransportTypeNavigation")
                        .WithMany("PublicTransports")
                        .HasForeignKey("TransportType")
                        .HasConstraintName("FK_PublicTransport_PublicTransportTypes");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany("PublicTransportUpdatedBies")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("AssigneeNavigation");

                    b.Navigation("CreatedBy");

                    b.Navigation("DriverNavigation");

                    b.Navigation("Job");

                    b.Navigation("StatusNavigation");

                    b.Navigation("TransportTypeNavigation");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Purchase", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "AssigneeNavigation")
                        .WithMany("PurchaseAssigneeNavigations")
                        .HasForeignKey("Assignee")
                        .HasConstraintName("FK_Purchase_Users1");

                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany("PurchaseCreatedBies")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.User", "DriverNavigation")
                        .WithMany("PurchaseDriverNavigations")
                        .HasForeignKey("Driver")
                        .HasConstraintName("FK_Purchase_Users");

                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("Purchases")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Purchase_Jobs");

                    b.HasOne("TruckMove.API.DAL.Models.TaskStatus", "StatusNavigation")
                        .WithMany("Purchases")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK_Purchase_TaskStatus");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany("PurchaseUpdatedBies")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("AssigneeNavigation");

                    b.Navigation("CreatedBy");

                    b.Navigation("DriverNavigation");

                    b.Navigation("Job");

                    b.Navigation("StatusNavigation");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Trailer", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.HookupType", "HookupTypeNavigation")
                        .WithMany("Trailers")
                        .HasForeignKey("HookupType")
                        .IsRequired()
                        .HasConstraintName("FK_Trailers_HookupTypes");

                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("Trailers")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_Trailers_Jobs");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("HookupTypeNavigation");

                    b.Navigation("Job");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.User", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany("InverseCreatedBy")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany("InverseUpdatedBy")
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.UserRole", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany("UserRoleCreatedBies")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany("UserRoleUpdatedBies")
                        .HasForeignKey("UpdatedById");

                    b.HasOne("TruckMove.API.DAL.Models.User", "User")
                        .WithMany("UserRoleUsers")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Role");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Vehicle", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("TruckMove.API.DAL.Models.Job", "JobNavigation")
                        .WithOne("VehicleNavigation")
                        .HasForeignKey("TruckMove.API.DAL.Models.Vehicle", "JobId")
                        .IsRequired();

                    b.HasOne("TruckMove.API.DAL.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById");

                    b.Navigation("CreatedBy");

                    b.Navigation("JobNavigation");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.WayPoint", b =>
                {
                    b.HasOne("TruckMove.API.DAL.Models.Job", "Job")
                        .WithMany("WayPoints")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_WayPoints_Jobs");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Accommodation", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Checklist", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Company", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Contact", b =>
                {
                    b.Navigation("JobContacts");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.HookupType", b =>
                {
                    b.Navigation("Trailers");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Job", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Acknowledgements");

                    b.Navigation("Checklists");

                    b.Navigation("Images");

                    b.Navigation("JobContacts");

                    b.Navigation("Legs");

                    b.Navigation("Notes");

                    b.Navigation("PermitsAndPlates");

                    b.Navigation("PublicTransports");

                    b.Navigation("Purchases");

                    b.Navigation("Trailers");

                    b.Navigation("VehicleNavigation");

                    b.Navigation("WayPoints");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.JobStatus", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Leg", b =>
                {
                    b.Navigation("Acknowledgement");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.LegStatus", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.PermitsAndPlate", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.PublicTransport", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.PublicTransportType", b =>
                {
                    b.Navigation("PublicTransports");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.TaskStatus", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("PermitsAndPlates");

                    b.Navigation("PublicTransports");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Trailer", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.User", b =>
                {
                    b.Navigation("AccommodationAssigneeNavigations");

                    b.Navigation("AccommodationCreatedBies");

                    b.Navigation("AccommodationDriverNavigations");

                    b.Navigation("AccommodationUpdatedBies");

                    b.Navigation("CompanyCreatedBies");

                    b.Navigation("CompanyUpdatedBies");

                    b.Navigation("ContactCreatedBies");

                    b.Navigation("ContactUpdatedBies");

                    b.Navigation("InverseCreatedBy");

                    b.Navigation("InverseUpdatedBy");

                    b.Navigation("JobControllerNavigations");

                    b.Navigation("JobCreatedBies");

                    b.Navigation("JobDriverNavigations");

                    b.Navigation("JobUpdatedBies");

                    b.Navigation("PermitsAndPlates");

                    b.Navigation("PermitsAndPlatesCreatedBies");

                    b.Navigation("PermitsAndPlatesUpdatedBies");

                    b.Navigation("PublicTransportAssigneeNavigations");

                    b.Navigation("PublicTransportCreatedBies");

                    b.Navigation("PublicTransportDriverNavigations");

                    b.Navigation("PublicTransportUpdatedBies");

                    b.Navigation("PurchaseAssigneeNavigations");

                    b.Navigation("PurchaseCreatedBies");

                    b.Navigation("PurchaseDriverNavigations");

                    b.Navigation("PurchaseUpdatedBies");

                    b.Navigation("UserRoleCreatedBies");

                    b.Navigation("UserRoleUpdatedBies");

                    b.Navigation("UserRoleUsers");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Variance", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("TruckMove.API.DAL.Models.Vehicle", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Job");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
